version: '3.8'

services:
  backend:
    container_name: docker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
