apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: liciasantos/fastapi-hello
          ports:
            - containerPort: 8000  # essa porta tem que bater com o que o FastAPI usa

