apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000        # porta do service dentro do cluster
      targetPort: 8000  # porta do container
      nodePort: 30001   # porta exposta para acesso externo
  type: NodePort



