apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000        # Porta exposta pelo service dentro do cluster
      targetPort: 8000  # Porta que o container está ouvindo
      nodePort: 30001   # Porta externa na VM para acessar via NodePort
  type: NodePort



